apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-backend
spec:
  selector:
    matchLabels:
      app: fintech-backend
  template:
    metadata:
      labels:
        app: fintech-backend
    spec:
      containers:
      - name: fintech-backend
        image: docker.io/vishalbagdi/fintech-backend
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_HOST
          value: mongo.fintech.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: fintech-backend
spec:
  selector:
    app: fintech-backend
  ports:
  - port: 80
    targetPort: 8000
          
